import 'package:hive/hive.dart';
import 'package:math_quiz_game/model/equation_model.dart';

Future<void> saveInitialData() async {
  final box = Hive.box<EquationModel>('equations');

  if (box.isEmpty) {
    final data = [
      EquationModel(
        id: 0,
        equation: "Loading",
        solution: [0],
        solved: false,
        steps: ["Loading"],
      ),
      EquationModel(
        id: 1,
        equation: "x + 3 = 5",
        solution: [2],
        solved: false,
        steps: [
          "x + 3 = 5",
          "Subtract 3 from both sides",
          "x + 3 - 3 = 5 - 3",
          "x = 2",
        ],
      ),
      EquationModel(
        id: 2,
        equation: "x - 4 = 6",
        solution: [10],
        solved: false,
        steps: [
          "x - 4 = 6",
          "Add 4 to both sides",
          "x - 4 + 4 = 6 + 4",
          "x = 10",
        ],
      ),
      EquationModel(
        id: 3,
        equation: "2x = 8",
        solution: [4],
        solved: false,
        steps: ["2x = 8", "Divide both sides by 2", "2x / 2 = 8 / 2", "x = 4"],
      ),
      EquationModel(
        id: 4,
        equation: "3x = 15",
        solution: [5],
        solved: false,
        steps: [
          "3x = 15",
          "Divide both sides by 3",
          "3x / 3 = 15 / 3",
          "x = 5",
        ],
      ),
      EquationModel(
        id: 5,
        equation: "x / 2 = 3",
        solution: [6],
        solved: false,
        steps: [
          "x / 2 = 3",
          "Multiply both sides by 2",
          "(x / 2) * 2 = 3 * 2",
          "x = 6",
        ],
      ),
      EquationModel(
        id: 6,
        equation: "x + 7 = 10",
        solution: [3],
        solved: false,
        steps: [
          "x + 7 = 10",
          "Subtract 7 from both sides",
          "x + 7 - 7 = 10 - 7",
          "x = 3",
        ],
      ),
      EquationModel(
        id: 7,
        equation: "x - 2 = 0",
        solution: [2],
        solved: false,
        steps: [
          "x - 2 = 0",
          "Add 2 to both sides",
          "x - 2 + 2 = 0 + 2",
          "x = 2",
        ],
      ),
      EquationModel(
        id: 8,
        equation: "4x = 20",
        solution: [5],
        solved: false,
        steps: [
          "4x = 20",
          "Divide both sides by 4",
          "4x / 4 = 20 / 4",
          "x = 5",
        ],
      ),
      EquationModel(
        id: 9,
        equation: "x / 5 = 2",
        solution: [10],
        solved: false,
        steps: [
          "x / 5 = 2",
          "Multiply both sides by 5",
          "(x / 5) * 5 = 2 * 5",
          "x = 10",
        ],
      ),
      EquationModel(
        id: 10,
        equation: "x + 1 = 4",
        solution: [3],
        solved: false,
        steps: [
          "x + 1 = 4",
          "Subtract 1 from both sides",
          "x + 1 - 1 = 4 - 1",
          "x = 3",
        ],
      ),
      EquationModel(
        id: 11,
        equation: "x - 3 = 3",
        solution: [6] ,
        solved: false,
        steps: [
          "x - 3 = 3",
          "Add 3 to both sides",
          "x - 3 + 3 = 3 + 3",
          "x = 6",
        ],
      ),
      EquationModel(
        id: 12,
        equation: "x / 4 = 1",
        solution: [4],
        solved: false,
        steps: [
          "x / 4 = 1",
          "Multiply both sides by 4",
          "(x / 4) * 4 = 1 * 4",
          "x = 4",
        ],
      ),
      EquationModel(
        id: 13,
        equation: "5x = 25",
        solution: [5],
        solved: false,
        steps: [
          "5x = 25",
          "Divide both sides by 5",
          "5x / 5 = 25 / 5",
          "x = 5",
        ],
      ),
      EquationModel(
        id: 14,
        equation: "x + 6 = 9",
        solution: [3],
        solved: false,
        steps: [
          "x + 6 = 9",
          "Subtract 6 from both sides",
          "x + 6 - 6 = 9 - 6",
          "x = 3",
        ],
      ),
      EquationModel(
        id: 15,
        equation: "x - 1 = 1",
        solution: [2],
        solved: false,
        steps: [
          "x - 1 = 1",
          "Add 1 to both sides",
          "x - 1 + 1 = 1 + 1",
          "x = 2",
        ],
      ),
      EquationModel(
        id: 16,
        equation: "2x = 6",
        solution: [3],
        solved: false,
        steps: ["2x = 6", "Divide both sides by 2", "2x / 2 = 6 / 2", "x = 3"],
      ),
      EquationModel(
        id: 17,
        equation: "3x = 12",
        solution: [4],
        solved: false,
        steps: [
          "3x = 12",
          "Divide both sides by 3",
          "3x / 3 = 12 / 3",
          "x = 4",
        ],
      ),
      EquationModel(
        id: 18,
        equation: "x / 3 = 2",
        solution: [6],
        solved: false,
        steps: [
          "x / 3 = 2",
          "Multiply both sides by 3",
          "(x / 3) * 3 = 2 * 3",
          "x = 6",
        ],
      ),
      EquationModel(
        id: 19,
        equation: "x + 5 = 8",
        solution: [3],
        solved: false,
        steps: [
          "x + 5 = 8",
          "Subtract 5 from both sides",
          "x + 5 - 5 = 8 - 5",
          "x = 3",
        ],
      ),
      EquationModel(
        id: 20,
        equation: "x - 6 = 0",
        solution: [6],
        solved: false,
        steps: [
          "x - 6 = 0",
          "Add 6 to both sides",
          "x - 6 + 6 = 0 + 6",
          "x = 6",
        ],
      ),
      EquationModel(
        id: 21,
        equation: "x / 2 = 5",
        solution: [10],
        solved: false,
        steps: [
          "x / 2 = 5",
          "Multiply both sides by 2",
          "(x / 2) * 2 = 5 * 2",
          "x = 10",
        ],
      ),
      EquationModel(
        id: 22,
        equation: "6x = 12",
        solution: [2] ,
        solved: false,
        steps: [
          "6x = 12",
          "Divide both sides by 6",
          "6x / 6 = 12 / 6",
          "x = 2",
        ],
      ),
      EquationModel(
        id: 23,
        equation: "x + 4 = 7",
        solution: [3],
        solved: false,
        steps: [
          "x + 4 = 7",
          "Subtract 4 from both sides",
          "x + 4 - 4 = 7 - 4",
          "x = 3",
        ],
      ),
      EquationModel(
        id: 24,
        equation: "x - 5 = 2",
        solution: [7],
        solved: false,
        steps: [
          "x - 5 = 2",
          "Add 5 to both sides",
          "x - 5 + 5 = 2 + 5",
          "x = 7",
        ],
      ),
      EquationModel(
        id: 25,
        equation: "7x = 21",
        solution: [3],
        solved: false,
        steps: [
          "7x = 21",
          "Divide both sides by 7",
          "7x / 7 = 21 / 7",
          "x = 3",
        ],
      ),
      EquationModel(
        id: 26,
        equation: "x / 7 = 1",
        solution: [7],
        solved: false,
        steps: [
          "x / 7 = 1",
          "Multiply both sides by 7",
          "(x / 7) * 7 = 1 * 7",
          "x = 7",
        ],
      ),
      EquationModel(
        id: 27,
        equation: "x + 2 = 6",
        solution: [4],
        solved: false,
        steps: [
          "x + 2 = 6",
          "Subtract 2 from both sides",
          "x + 2 - 2 = 6 - 2",
          "x = 4",
        ],
      ),
      EquationModel(
        id: 28,
        equation: "x - 8 = 0",
        solution: [8],
        solved: false,
        steps: [
          "x - 8 = 0",
          "Add 8 to both sides",
          "x - 8 + 8 = 0 + 8",
          "x = 8",
        ],
      ),
      EquationModel(
        id: 29,
        equation: "x + 10 = 13",
        solution: [3],
        solved: false,
        steps: [
          "x + 10 = 13",
          "Subtract 10 from both sides",
          "x + 10 - 10 = 13 - 10",
          "x = 3",
        ],
      ),
      EquationModel(
        id: 30,
        equation: "x / 6 = 2",
        solution: [12],
        solved: false,
        steps: [
          "x / 6 = 2",
          "Multiply both sides by 6",
          "(x / 6) * 6 = 2 * 6",
          "x = 12",
        ],
      ),
      EquationModel(
        id: 31,
        equation: "2x + 3 = 9",
        solution: [3],
        solved: false,
        steps: [
          "2x + 3 = 9",
          "Subtract 3 from both sides",
          "2x = 6",
          "Divide both sides by 2",
          "x = 3",
        ],
      ),
      EquationModel(
        id: 32,
        equation: "5x - 4 = 21",
        solution: [5],
        solved: false,
        steps: [
          "5x - 4 = 21",
          "Add 4 to both sides",
          "5x = 25",
          "Divide both sides by 5",
          "x = 5",
        ],
      ),
      EquationModel(
        id: 33,
        equation: "3x + 2 = 17",
        solution: [5],
        solved: false,
        steps: [
          "3x + 2 = 17",
          "Subtract 2 from both sides",
          "3x = 15",
          "Divide both sides by 3",
          "x = 5",
        ],
      ),
      EquationModel(
        id: 34,
        equation: "4x - 7 = 9",
        solution: [4],
        solved: false,
        steps: [
          "4x - 7 = 9",
          "Add 7 to both sides",
          "4x = 16",
          "Divide both sides by 4",
          "x = 4",
        ],
      ),
      EquationModel(
        id: 35,
        equation: "2(x - 3) = 8",
        solution: [7],
        solved: false,
        steps: [
          "2(x - 3) = 8",
          "Divide both sides by 2",
          "x - 3 = 4",
          "Add 3 to both sides",
          "x = 7",
        ],
      ),
      EquationModel(
        id: 36,
        equation: "3(x + 2) = 15",
        solution: [3],
        solved: false,
        steps: [
          "3(x + 2) = 15",
          "Divide both sides by 3",
          "x + 2 = 5",
          "Subtract 2 from both sides",
          "x = 3",
        ],
      ),
      EquationModel(
        id: 37,
        equation: "x/2 + 5 = 9",
        solution: [8],
        solved: false,
        steps: [
          "x/2 + 5 = 9",
          "Subtract 5 from both sides",
          "x/2 = 4",
          "Multiply both sides by 2",
          "x = 8",
        ],
      ),
      EquationModel(
        id: 38,
        equation: "x/3 - 2 = 1",
        solution: [9],
        solved: false,
        steps: [
          "x/3 - 2 = 1",
          "Add 2 to both sides",
          "x/3 = 3",
          "Multiply both sides by 3",
          "x = 9",
        ],
      ),
      EquationModel(
        id: 39,
        equation: "6x + 4 = 28",
        solution: [4],
        solved: false,
        steps: [
          "6x + 4 = 28",
          "Subtract 4 from both sides",
          "6x = 24",
          "Divide both sides by 6",
          "x = 4",
        ],
      ),
      EquationModel(
        id: 40,
        equation: "2x - 5 = 3x + 2",
        solution: [-7],
        solved: false,
        steps: [
          "2x - 5 = 3x + 2",
          "Subtract 2x from both sides",
          "-5 = x + 2",
          "Subtract 2 from both sides",
          "-7 = x",
          "x = -7",
        ],
      ),
      EquationModel(
        id: 41,
        equation: "4x + 6 = 2x + 10",
        solution: [2],
        solved: false,
        steps: [
          "4x + 6 = 2x + 10",
          "Subtract 2x from both sides",
          "2x + 6 = 10",
          "Subtract 6 from both sides",
          "2x = 4",
          "x = 2",
        ],
      ),
      EquationModel(
        id: 42,
        equation: "7x - 3 = 4x + 6",
        solution: [3],
        solved: false,
        steps: [
          "7x - 3 = 4x + 6",
          "Subtract 4x from both sides",
          "3x - 3 = 6",
          "Add 3 to both sides",
          "3x = 9",
          "x = 3",
        ],
      ),
      EquationModel(
        id: 43,
        equation: "5(x + 1) = 20",
        solution: [3],
        solved: false,
        steps: [
          "5(x + 1) = 20",
          "Divide both sides by 5",
          "x + 1 = 4",
          "Subtract 1 from both sides",
          "x = 3",
        ],
      ),
      EquationModel(
        id: 44,
        equation: "x/4 + 2 = 6",
        solution: [16],
        solved: false,
        steps: [
          "x/4 + 2 = 6",
          "Subtract 2 from both sides",
          "x/4 = 4",
          "Multiply both sides by 4",
          "x = 16",
        ],
      ),
      EquationModel(
        id: 45,
        equation: "3x + 5 = x + 15",
        solution: [5],
        solved: false,
        steps: [
          "3x + 5 = x + 15",
          "Subtract x from both sides",
          "2x + 5 = 15",
          "Subtract 5 from both sides",
          "2x = 10",
          "x = 5",
        ],
      ),
      EquationModel(
        id: 46,
        equation: "6(x - 2) = 24",
        solution: [6],
        solved: false,
        steps: [
          "6(x - 2) = 24",
          "Divide both sides by 6",
          "x - 2 = 4",
          "Add 2 to both sides",
          "x = 6",
        ],
      ),
      EquationModel(
        id: 47,
        equation: "8x - 4 = 2x + 14",
        solution: [3],
        solved: false,
        steps: [
          "8x - 4 = 2x + 14",
          "Subtract 2x from both sides",
          "6x - 4 = 14",
          "Add 4 to both sides",
          "6x = 18",
          "x = 3",
        ],
      ),
      EquationModel(
        id: 48,
        equation: "x/5 - 1 = 3",
        solution: [20],
        solved: false,
        steps: [
          "x/5 - 1 = 3",
          "Add 1 to both sides",
          "x/5 = 4",
          "Multiply both sides by 5",
          "x = 20",
        ],
      ),
      EquationModel(
        id: 49,
        equation: "9x + 2 = 3x + 20",
        solution: [3],
        solved: false,
        steps: [
          "9x + 2 = 3x + 20",
          "Subtract 3x from both sides",
          "6x + 2 = 20",
          "Subtract 2 from both sides",
          "6x = 18",
          "x = 3",
        ],
      ),
      EquationModel(
        id: 50,
        equation: "x - 3 = 2x + 4",
        solution: [-7],
        solved: false,
        steps: [
          "x - 3 = 2x + 4",
          "Subtract x from both sides",
          "-3 = x + 4",
          "Subtract 4 from both sides",
          "-7 = x",
          "x = -7",
        ],
      ),
      EquationModel(
        id: 51,
        equation: "4x + 8 = 2(x + 6)",
        solution: [2],
        solved: false,
        steps: [
          "4x + 8 = 2(x + 6)",
          "Expand right side: 4x + 8 = 2x + 12",
          "Subtract 2x from both sides",
          "2x + 8 = 12",
          "Subtract 8 from both sides",
          "2x = 4",
          "x = 2",
        ],
      ),
      EquationModel(
        id: 52,
        equation: "10 - 2x = 4x - 2",
        solution: [2],
        solved: false,
        steps: [
          "10 - 2x = 4x - 2",
          "Add 2x to both sides",
          "10 = 6x - 2",
          "Add 2 to both sides",
          "12 = 6x",
          "x = 2",
        ],
      ),
      EquationModel(
        id: 53,
        equation: "x/2 + x/4 = 6",
        solution: [4],
        solved: false,
        steps: [
          "x/2 + x/4 = 6",
          "Find common denominator: 2x/4 + x/4 = 6",
          "Combine terms: 3x/4 = 6",
          "Multiply both sides by 4: 3x = 24",
          "Divide by 3: x = 4",
        ],
      ),
      EquationModel(
        id: 54,
        equation: "7(x - 1) = x + 18",
        solution: [3],
        solved: false,
        steps: [
          "7(x - 1) = x + 18",
          "Expand left: 7x - 7 = x + 18",
          "Subtract x from both sides: 6x - 7 = 18",
          "Add 7: 6x = 25",
          "Divide: x = 25/6 ≈ 4.17",
        ],
      ),
      EquationModel(
        id: 55,
        equation: "3x + 2 = 2x + 5",
        solution: [3],
        solved: false,
        steps: [
          "3x + 2 = 2x + 5",
          "Subtract 2x: x + 2 = 5",
          "Subtract 2: x = 3",
        ],
      ),
      EquationModel(
        id: 56,
        equation: "x/3 + x/6 = 6",
        solution: [4],
        solved: false,
        steps: [
          "x/3 + x/6 = 6",
          "Common denominator: 2x/6 + x/6 = 6",
          "Combine: 3x/6 = 6",
          "Simplify: x/2 = 6",
          "Multiply by 2: x = 12",
        ],
      ),
      EquationModel(
        id: 57,
        equation: "2(x + 4) = x + 10",
        solution: [2],
        solved: false,
        steps: [
          "2(x + 4) = x + 10",
          "Expand: 2x + 8 = x + 10",
          "Subtract x: x + 8 = 10",
          "Subtract 8: x = 2",
        ],
      ),
      EquationModel(
        id: 58,
        equation: "5x - 3 = 2x + 12",
        solution: [5],
        solved: false,
        steps: [
          "5x - 3 = 2x + 12",
          "Subtract 2x: 3x - 3 = 12",
          "Add 3: 3x = 15",
          "Divide: x = 5",
        ],
      ),
      EquationModel(
        id: 59,
        equation: "x - (3x + 4) = 6",
        solution: [-5],
        solved: false,
        steps: [
          "x - (3x + 4) = 6",
          "Distribute minus: x - 3x - 4 = 6",
          "-2x - 4 = 6",
          "Add 4: -2x = 10",
          "Divide: x = -5",
        ],
      ),
      EquationModel(
        id: 60,
        equation: "2(x - 1) + 3 = x + 5",
        solution: [4],
        solved: false,
        steps: [
          "2(x - 1) + 3 = x + 5",
          "Expand: 2x - 2 + 3 = x + 5",
          "Simplify: 2x + 1 = x + 5",
          "Subtract x: x + 1 = 5",
          "Subtract 1: x = 4",
        ],
      ),
      EquationModel(
        id: 61,
        equation: "x + y = 10\nx - y = 2",
        solution: [6,4],
        solved: false,
        steps: [
          "x + y = 10",
          "x - y = 2",
          "Add the two equations: (x + y) + (x - y) = 10 + 2",
          "2x = 12",
          "x = 6",
          "Substitute x = 6 into first equation: 6 + y = 10",
          "y = 4",
        ],
      ),
      EquationModel(
        id: 62,
        equation: "2x + 3y = 12\nx + y = 5",
        solution: [3,2],
        solved: false,
        steps: [
          "From x + y = 5, express x = 5 - y",
          "Substitute in first equation: 2(5 - y) + 3y = 12",
          "10 - 2y + 3y = 12",
          "y = 2",
          "x = 5 - 2 = 3",
        ],
      ),
      EquationModel(
        id: 63,
        equation: "x + 2y = 7\nx - y = 1",
        solution: [3,2],
        solved: false,
        steps: [
          "From x - y = 1, express x = y + 1",
          "Substitute into first equation: y + 1 + 2y = 7",
          "3y + 1 = 7",
          "3y = 6",
          "y = 2, x = 3",
        ],
      ),
      EquationModel(
        id: 64,
        equation: "3x - 2y = 4\nx + y = 5",
        solution: ["14/5", "11/5"],
        solved: false,
        steps: [
          "From x + y = 5, express x = 5 - y",
          "Substitute into first equation: 3(5 - y) - 2y = 4",
          "15 - 3y - 2y = 4",
          "15 - 5y = 4",
          "5y = 11",
          "y = 11/5, x = 5 - 11/5 = 14/5",
        ],
      ),
      EquationModel(
        id: 65,
        equation: "2x + y = 8\nx - y = 1",
        solution: [3,2],
        solved: false,
        steps: [
          "Add equations: 2x + y + x - y = 8 + 1",
          "3x = 9",
          "x = 3",
          "Substitute into second equation: 3 - y = 1",
          "y = 2",
        ],
      ),
      EquationModel(
        id: 66,
        equation: "x + y = 6\n2x - y = 3",
        solution: [3,3],
        solved: false,
        steps: [
          "From x + y = 6, express y = 6 - x",
          "Substitute into second: 2x - (6 - x) = 3",
          "2x - 6 + x = 3",
          "3x = 9",
          "x = 3, y = 3",
        ],
      ),
      EquationModel(
        id: 67,
        equation: "x + 3y = 9\nx - y = 1",
        solution: [3,2] ,
        solved: false,
        steps: [
          "From x - y = 1, express x = y + 1",
          "Substitute in first: y + 1 + 3y = 9",
          "4y + 1 = 9",
          "4y = 8",
          "y = 2, x = 3",
        ],
      ),
      EquationModel(
        id: 68,
        equation: "2x + 4y = 16\nx - 2y = 2",
        solution: [5,1.5],
        solved: false,
        steps: [
          "Simplify first: divide by 2: x + 2y = 8",
          "x - 2y = 2",
          "Add both: x + 2y + x - 2y = 8 + 2",
          "2x = 10",
          "x = 5, then x - 2y = 2 → 5 - 2y = 2 → y = 1.5",
        ],
      ),
      EquationModel(
        id: 69,
        equation: "x + y = 4\nx + 2y = 7",
        solution: [1,3],
        solved: false,
        steps: [
          "Subtract first from second: (x + 2y) - (x + y) = 7 - 4",
          "x + 2y - x - y = 3",
          "y = 3, x = 1",
        ],
      ),
      EquationModel(
        id: 70,
        equation: "4x + y = 11\n2x - y = 1",
        solution: [2,3],
        solved: false,
        steps: [
          "Add equations: 4x + y + 2x - y = 11 + 1",
          "6x = 12",
          "x = 2, then 2x - y = 1 → 4 - y = 1 → y = 3",
        ],
      ),
      EquationModel(
        id: 71,
        equation: "x - y = 5\nx + y = 1",
        solution: [3,-2],
        solved: false,
        steps: [
          "Add both: x - y + x + y = 5 + 1",
          "2x = 6",
          "x = 3, then x + y = 1 → 3 + y = 1 → y = -2",
        ],
      ),
      EquationModel(
        id: 72,
        equation: "3x + 2y = 12\nx - y = 1",
        solution: [2.8,1.8],
        solved: false,
        steps: [
          "From x - y = 1, x = y + 1",
          "Sub into first: 3(y + 1) + 2y = 12",
          "3y + 3 + 2y = 12",
          "5y = 9 → y = 1.8, x = 2.8",
        ],
      ),
      EquationModel(
        id: 73,
        equation: "5x + y = 13\nx - y = 1",
        solution: [2.33,1.33],
        solved: false,
        steps: [
          "From x - y = 1, x = y + 1",
          "Sub into first: 5(y + 1) + y = 13",
          "5y + 5 + y = 13",
          "6y = 8 → y = 1.33, x = 2.33",
        ],
      ),
      EquationModel(
        id: 74,
        equation: "x + 2y = 10\n3x - y = 5",
        solution: ["20/7","25/7"],
        solved: false,
        steps: [
          "From x + 2y = 10, x = 10 - 2y",
          "Sub into second: 3(10 - 2y) - y = 5",
          "30 - 6y - y = 5",
          "-7y = -25 → y = 25/7",
          "x = 10 - 2*(25/7) = 10 - 50/7 = 20/7",
        ],
      ),
      EquationModel(
        id: 75,
        equation: "x - 3y = -2\n2x + y = 11",
        solution: ["31/7","15/7"],
        solved: false,
        steps: [
          "From x - 3y = -2, x = 3y - 2",
          "Sub into second: 2(3y - 2) + y = 11",
          "6y - 4 + y = 11",
          "7y = 15 → y = 15/7, x = 3*(15/7) - 2 = 45/7 - 2 = 31/7",
        ],
      ),
      EquationModel(
        id: 76,
        equation: "3x + 2y = 16\n5x - 3y = 7",
        solution: [3.26,3.11],
        solved: false,
        steps: [
          "Multiply first equation by 3 and second by 2 to eliminate y:",
          "9x + 6y = 48",
          "10x - 6y = 14",
          "Add both equations: 19x = 62",
          "x = 62 / 19 = 3.26",
          "Substitute x into first: 3(3.26) + 2y = 16 → 9.78 + 2y = 16",
          "2y = 6.22 → y = 3.11",
        ],
      ),
      EquationModel(
        id: 77,
        equation: "2x/3 + y/2 = 5\nx/4 - y/3 = 1",
        solution: [6.24,1.68],
        solved: false,
        steps: [
          "Multiply equations to eliminate denominators:",
          "1st eq *6: 4x + 3y = 30",
          "2nd eq *12: 3x - 4y = 12",
          "Now solve using elimination",
          "Multiply 1st by 4: 16x + 12y = 120",
          "Multiply 2nd by 3: 9x - 12y = 36",
          "Add: 25x = 156 → x = 6.24",
          "Back-substitute to find y",
        ],
      ),
      EquationModel(
        id: 78,
        equation: "4x - 5y = 13\n-6x + 7y = -11",
        solution: [-18,-17],
        solved: false,
        steps: [
          "Multiply 1st by 6 and 2nd by 4:",
          "24x - 30y = 78",
          "-24x + 28y = -44",
          "Add: -2y = 34 → y = -17",
          "Sub into 1st: 4x + 85 = 13 → 4x = -72 → x = -18",
        ],
      ),
      EquationModel(
        id: 79,
        equation: "x/2 + y/3 = 5\nx/4 - y/2 = 1",
        solution: [8.5,2.25],
        solved: false,
        steps: [
          "Multiply both equations to eliminate fractions:",
          "1st *6: 3x + 2y = 30",
          "2nd *4: x - 2y = 4",
          "Add: 4x = 34 → x = 8.5",
          "Substitute: 8.5 - 2y = 4 → y = 2.25",
        ],
      ),
      EquationModel(
        id: 80,
        equation: "x + y = 7\n2x + 3y = 18",
        solution: [3,4],
        solved: false,
        steps: [
          "From 1st: x = 7 - y",
          "Sub into 2nd: 2(7 - y) + 3y = 18",
          "14 - 2y + 3y = 18",
          "y = 4, x = 3",
        ],
      ),
      // EASY
      EquationModel(
        id: 81,
        equation: "x + y + z = 6\ny + z = 4\nz = 1",
        solution: [1,3,1],
        solved: false,
        steps: [
          "Given: z = 1",
          "Substitute into 2nd: y + 1 = 4 → y = 3",
          "Substitute y and z into 1st: x + 3 + 1 = 6 → x = 2",
          "Final solution: x = 2, y = 3, z = 1",
        ],
      ),
      EquationModel(
        id: 82,
        equation: "x + 2y + z = 9\nx + y = 5\nz = 2",
        solution: [3,2,2],
        solved: false,
        steps: [
          "Given: z = 2",
          "x + y = 5 → x = 5 - y",
          "Sub into 1st: (5 - y) + 2y + 2 = 9",
          "5 - y + 2y + 2 = 9 → y = 2",
          "x = 5 - 2 = 3",
          "Final solution: x = 3, y = 2, z = 2",
        ],
      ),
      EquationModel(
        id: 83,
        equation: "x + y + z = 3\nx - y + z = 1\nx + y - z = 1",
        solution: [1,1,1],
        solved: false,
        steps: [
          "Add eq1 and eq2: 2x + 2z = 4 → x + z = 2",
          "Add eq1 and eq3: 2x + 2y = 4 → x + y = 2",
          "From x + z = 2 and x + y = 2 → y = z",
          "Substitute into eq1: x + y + y = 3 → x + 2y = 3",
          "From x + y = 2 → x = 2 - y",
          "2 - y + 2y = 3 → y = 1, x = 1, z = 1",
        ],
      ),

      // MEDIUM
      EquationModel(
        id: 84,
        equation: "2x + y - z = 8\n-x + 3y + 2z = -4\n3x - 2y + 4z = 10",
        solution: [3,2,-2],
        solved: false,
        steps: [
          "Use equation 1 and 2 to eliminate x:",
          "Multiply 1st by 1, 2nd by 2: 2x + y - z = 8 and -2x + 6y + 4z = -8",
          "Add: 7y + 3z = 0 → eq(4)",
          "Use eq1 and eq3 to eliminate x:",
          "3*(2x + y - z) = 6x + 3y - 3z = 24",
          "Subtract eq3: (6x + 3y - 3z) - (3x - 2y + 4z) = 3x + 5y - 7z = 14 → eq(5)",
          "Solve eq(4) and eq(5): y = 2, z = -2, x = 3",
        ],
      ),
      EquationModel(
        id: 85,
        equation: "x + 2y + z = 4\n2x + 3y + z = 7\n3x + y + 2z = 8",
        solution: [1,2,-1],
        solved: false,
        steps: [
          "Subtract eq1 from eq2: x + y = 3 → eq(4)",
          "Subtract eq1 from eq3: 2x - y + z = 4 → eq(5)",
          "From eq1: z = 4 - x - 2y",
          "Sub z into eq(5) and use eq(4) to solve",
          "Result: x = 1, y = 2, z = -1",
        ],
      ),
      EquationModel(
        id: 86,
        equation: "x + y + z = 10\nx + 2y + 3z = 24\n2x + 3y + z = 18",
        solution: [3,4,3],
        solved: false,
        steps: [
          "Use elimination and substitution:",
          "From eq1: x = 10 - y - z",
          "Sub into eq2 and eq3 → get two equations in y and z",
          "Solve those: y = 3, z = 4, x = 3",
        ],
      ),
      EquationModel(
        id: 87,
        equation: "2x + 3y - z = 1\n4x + y + 2z = 12\n3x - 2y + z = 3",
        solution: [2,1,-1],
        solved: false,
        steps: [
          "Use Gaussian elimination:",
          "First eliminate z between eq1 and eq2",
          "Then eliminate x and y to get z",
          "Back-substitute to get y and x",
          "Solution: x = 2, y = 1, z = -1",
        ],
      ),

      // HARD
      EquationModel(
        id: 88,
        equation: "x - y + z = 2\n2x + y - 3z = -1\n3x + 4y + 2z = 10",
        solution: [1,2,2],
        solved: false,
        steps: [
          "Use matrix method or elimination:",
          "From eq1: x = y - z + 2",
          "Substitute into other equations to eliminate x",
          "Get two equations in y and z",
          "Solve to get y = 1, z = 2, x = 1",
        ],
      ),
      EquationModel(
        id: 89,
        equation: "x + 2y + 3z = 14\n2x + y + z = 10\n4x + 5y + 6z = 32",
        solution: [2,3,2],
        solved: false,
        steps: [
          "Row reduce or eliminate:",
          "Multiply and subtract rows to eliminate x and y",
          "Solve two equations in z",
          "Then find y, and then x",
          "Final: x = 2, y = 3, z = 2",
        ],
      ),
      EquationModel(
        id: 90,
        equation: "x + y + z = 6\n2x + 3y + 5z = 19\n4x + 5y + 6z = 29",
        solution: [2,1,3],
        solved: false,
        steps: [
          "From eq1: x = 6 - y - z",
          "Sub into eq2 and eq3",
          "Get two-variable system: solve for y and z",
          "Then back-substitute to find x",
          "Solution: x = 2, y = 1, z = 3",
        ],
      ),
    ];

    for (var item in data) {
      await box.add(item);
    }
  }
}

void markAsSolved(int index) {
  final box = Hive.box<EquationModel>('equations');
  final item = box.getAt(index);
  item?.solved = true;
  item?.save();
}
